### ISSUE TITLE
TextView instead of Label

### ISSUE THREAD

**Issue by DavidLari** [mukeshthawani/FAQView#12]
If anyone is interested, I have created a [fork](https://github.com/DavidLari/FAQView) with the following enhancements:

* Replaced the answer UILabel with a UITextView.
* Added automatic data detection capability. Just set dataDetectorTypes property array to the types you want to detect and the detector will make them links in the answer.
* Added answerTintColor to color foreground text color of detected links.
* Added a new property to Items. You may initialize an item with either the answer String, or attributedAnswer as NSAttributedString. This allows the ability to add links. For example, you could give a brief answer to a question and provide a link for more information.

I needed these features for my app. If there is interest in merging these changes into this project, let me know. Otherwise, just close this issue and I'll maintain my own fork.

**Comment by mukeshthawani** [comment]
Please create a PR.

**Comment by mukeshthawani** [comment]
@DavidLari any updates?
