### ISSUE TITLE
Transition to landscape not handled correctly

### ISSUE THREAD

**Issue by andrewkouri-old** [mukeshthawani/FAQView#19]
When you start in portrait mode and transition to landscape, the formatting of the FAQ view does not update. See attached:

![img_2147](https://cloud.githubusercontent.com/assets/1635224/22604903/7479a47a-ea02-11e6-8fe6-1b800a6df8d9.PNG)

**Comment by DavidLari** [comment]
It must be something specific to your implementation. It's working perfectly for me. Are you sure you have constraints set correctly on whatever view you are adding the FAQView to?

**Comment by andrewkouri-old** [comment]
I believe so:

![screen shot 2017-02-03 at 4 42 52 pm](https://cloud.githubusercontent.com/assets/1635224/22613756/e8257dc2-ea2f-11e6-8d12-a0921ac43862.png)

![screen shot 2017-02-03 at 4 45 29 pm](https://cloud.githubusercontent.com/assets/1635224/22613791/37f0faac-ea30-11e6-97e1-5ee0fda7b5e1.png)


```
                    DispatchQueue.main.async {
                        let faqView = FAQView(frame: self.mainView.frame, items: self.items)
                        self.mainView.addSubview(faqView)
                    }
```

**Comment by DavidLari** [comment]
Okay, I think I know your problem. Check out the demo and look at this code:
https://github.com/mukeshthawani/FAQView/blob/master/Demo/ViewController.swift

You need to add constraints as shown there, except add them to your mainView instead of self.view.

**Comment by andrewkouri-old** [comment]
Ah, okay. Got it.  In my case, the problem was I forgot to set
```
    faqView.translatesAutoresizingMaskIntoConstraints = false
```

Thanks
