### ISSUE TITLE
Answer TextView Font always very small no way to change it

### ISSUE THREAD

**Issue by edelacruz-teravision** [mukeshthawani/FAQView#25]
No matter what font you set always appear very small in table

**Comment by DavidLari** [comment]
Are you setting the answer or the attributed answer?

**Comment by edelacruz-teravision** [comment]
Nop using this 

// Question text font
faqView.questionTextFont = UIFont(name: "HelveticaNeue-Light", size: 15)

by the way for Question wont work

**Comment by DavidLari** [comment]
I'm sorry. I don't understand the problem. You said the answer is too small, but your example here shows you are setting the question font.

**Comment by edelacruz-teravision** [comment]
Im going to try to explain my self...

i set the answer and question the same (no answer example in your github)

// Question text font
faqView.questionTextFont = UIFont(name: "SanFrancisco-Bold", size: 13)

// Answer text font
faqView.answerTextFont = UIFont(name: "SanFrancisco-Light", size: 13)

This is not workin... not for answer, not for question...

The only way i found to make it work was ...

// Question text font
faqView.questionTextFont = UIFont.systemFont(ofSize: 13, weight: UIFontWeightBold)

// Answer text font
faqView.answerTextFont = UIFont.systemFont(ofSize: 13, weight: UIFontWeightLight)

Same happens with tittleLabel

**Comment by edelacruz-teravision** [comment]
And i added in the FAQView(frame: self.view.frame, title: "Some Title", items: items, **separatorHight: CGFloat**) that should be nice of you to add it bacause , in my case, I needed thinner separators

**Comment by DavidLari** [comment]
So, the problem isn't with FAQView. Whatever device or simulator you are running must not have the font you are specifying. Have you checked to see if  UIFont(name: "SanFrancisco-Bold", size: 13) is actually returning a font?

**Comment by edelacruz-teravision** [comment]
If i’m not mistaken San Francisco font si the system font, i think i tested other fonts and had the dame result, ill test it again with other font name

**Comment by edelacruz-teravision** [comment]
https://developer.apple.com/fonts/

**Comment by DavidLari** [comment]
On an iPhone 7+ with iOS 11.1, when I run the following, it prints "x is nil". If you just want the system font anyway, just use UIFont.systemFont(ofSize: 13, weight: UIFontWeightBold).
```
let x = UIFont(name: "SanFrancisco-Light", size: 13)
if x == nil {
    print("x is nil")
}
```

**Comment by edelacruz-teravision** [comment]
Yep, that seems to be the Issue, tomorrow ill try the same code with different font names. thank you, by the way, for your fast reply
