### ISSUE TITLE
Enhancement - Option to open links in in-app (SafariViewController) browser

### ISSUE THREAD

**Issue by ghost** [mukeshthawani/FAQView#27]
It would be nice to have an option to open the links using SafariViewController (instead of taking the user to Safari) when user taps on the detected link.

**Comment by DavidLari** [comment]
It looks like this might be possible using the technique described here:
https://stackoverflow.com/questions/2543967/how-to-intercept-click-on-link-in-uitextview

**Comment by ghost** [comment]
@DavidLari 

Do you mean to say that this needs to be handled in the app which is integrating FAQView?

**Comment by DavidLari** [comment]
FAQView would need to be modified to give the option to pass a closure that would be the code the app wants to execute when a link is tapped. At least that's one way to implement it.

**Comment by ghost** [comment]
Thanks for the information. Hope to see this implemented in FAQView.

**Comment by mukeshthawani** [comment]
@ahamedsaifudeen If you were successful in implementing the above feature please feel free to contribute. We will be happy to accept the PR.
