### ISSUE TITLE
issue with constraints

### ISSUE THREAD

**Issue by X901** [mukeshthawani/FAQView#33]
Hi ,
I just tried the Demo project
and I get issues with constraints when I clicked on cell (after it expand)

> Unable to simultaneously satisfy constraints.
> 	Probably at least one of the constraints in the following list is one you don't want. 
> 	Try this: 
> 		(1) look at each constraint and try to figure out which you don't expect; 
> 		(2) find the code that added the unwanted constraint or constraints and fix it. 
> (
>     "<NSLayoutConstraint:0x60000272dea0 V:|-(10)-[UILabel:0x7fa285e0a030'What is reddit?']   (active, names: '|':UITableViewCellContentView:0x7fa285e04f20 )>",
>     "<NSLayoutConstraint:0x60000272ddb0 V:[UILabel:0x7fa285e0a030'What is reddit?']-(10)-[UITextView:0x7fa287007600'reddit is a source for wh...']   (active)>",
>     "<NSLayoutConstraint:0x60000272dd60 V:[UITextView:0x7fa287007600'reddit is a source for wh...']-(20)-|   (active, names: '|':UITableViewCellContentView:0x7fa285e04f20 )>",
>     "<NSLayoutConstraint:0x60000272db30 UIView:0x7fa285e04ba0.height == UILabel:0x7fa285e0a030'What is reddit?'.height   (active)>",
>     "<NSLayoutConstraint:0x60000277c690 'UIView-Encapsulated-Layout-Height' UITableViewCellContentView:0x7fa285e04f20.height == 38   (active)>"
> )
> 
> Will attempt to recover by breaking constraint 
> <NSLayoutConstraint:0x60000272ddb0 V:[UILabel:0x7fa285e0a030'What is reddit?']-(10)-[UITextView:0x7fa287007600'reddit is a source for wh...']   (active)>
> 
> Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
> The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
> ≈2020-02-11 14:16:27.754909+0300 Demo-iOS[11611:178060] [LayoutConstraints] Unable to simultaneously satisfy constraints.
> 	Probably at least one of the constraints in the following list is one you don't want. 
> 	Try this: 
> 		(1) look at each constraint and try to figure out which you don't expect; 
> 		(2) find the code that added the unwanted constraint or constraints and fix it. 
> (
>     "<NSLayoutConstraint:0x600002767b10 V:|-(10)-[UILabel:0x7fa288070790'How is a submission's sco...']   (active, names: '|':UITableViewCellContentView:0x7fa285c29cb0 )>",
>     "<NSLayoutConstraint:0x600002767c00 V:[UILabel:0x7fa288070790'How is a submission's sco...']-(10)-[UITextView:0x7fa28083a400'A submission's score is s...']   (active)>",
>     "<NSLayoutConstraint:0x600002767c50 V:[UITextView:0x7fa28083a400'A submission's score is s...']-(20)-|   (active, names: '|':UITableViewCellContentView:0x7fa285c29cb0 )>",
>     "<NSLayoutConstraint:0x600002767e80 UIView:0x7fa285c29710.height == UILabel:0x7fa288070790'How is a submission's sco...'.height   (active)>",
>     "<NSLayoutConstraint:0x60000272eee0 'UIView-Encapsulated-Layout-Height' UITableViewCellContentView:0x7fa285c29cb0.height == 38   (active)>"
> )
> 
> Will attempt to recover by breaking constraint 
> <NSLayoutConstraint:0x600002767c00 V:[UILabel:0x7fa288070790'How is a submission's sco...']-(10)-[UITextView:0x7fa28083a400'A submission's score is s...']   (active)>
> 
> Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
> The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
>

**Comment by kostapappas** [comment]
Even this project is too old, It's a problem with the VERTICAL constrains. You have a defined height == 38, but also you have restricted vertical rules for distances between the elements. Try to give priorities what rule is the most important in order to help autolayout to decide to do his best.

**Comment by X901** [comment]
@kostapappas Thank you I find the issue 
it was in 
and I add new feature also on PR

**Comment by mukeshthawani** [comment]
Merged your PR and released a new version. Thanks.
