### ISSUE TITLE
Feature Request: Image Tappable

### ISSUE THREAD

**Issue by DavidLari** [mukeshthawani/FAQView#5]
Currently, the down arrow image cannot be tapped to open/close the answer. I think many users will instinctively tap on the arrows. To make them respond to taps, the following code can be added to the tableView:cellForRowAt function.

Before the `return cell` add these four lines:

```
    cell.indicatorImageView.tag = indexPath.section
    let gestureRecogForImage = UITapGestureRecognizer(target: self, action: #selector(FAQView.handleQuestionLabelTap(_:)))
    cell.indicatorImageView.addGestureRecognizer(gestureRecogForImage)
    cell.indicatorImageView.isUserInteractionEnabled = true
```

**Comment by DavidLari** [comment]
I have also experimented with an alternate implementation. Instead of adding the gesture recognizer and tag to the question label, I just add it to the cell itself. This also seems to work.

**Comment by mukeshthawani** [comment]
I think it makes more sense to make only top part clickable like question and arrow icon.

**Comment by mukeshthawani** [comment]
There won't be any issue in the implementation of cell selection, it's default behavior of the tableview. Right now you expand the cell by clicking on the question or just say on the top part, and I think it should be same when you want to close the cell.

**Comment by mukeshthawani** [comment]
@DavidLari Could you please make a PR for this?

**Comment by DavidLari** [comment]
Sure. I am not very proficient with github yet, but I think I have created the PR. I added a gesture recognizer to the arrow. The answer label is not tappable.
