### ISSUE TITLE
Up/ down arrows don't appear

### ISSUE THREAD

**Issue by saldous** [mukeshthawani/FAQView#8]
I install via Cocoapods, copy / paste the code in the readme, run project and the arrows don't appear.

    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        
        faqView()
    }

    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    
    func faqView() {
        let items = [FAQItem(question: "What is reddit?", answer: "reddit is a source for what's new and popular on the web."),
                     FAQItem(question: "How is a submission's score determined?", answer: "A submission's score is simply the number of upvotes minus the number of downvotes.")]
        
        let faqListView = FAQView(frame: view.frame, items: items)
        view.addSubview(faqListView)
    }

![simulator screen shot jan 10 2017 9 13 29 am](https://cloud.githubusercontent.com/assets/3334306/21809307/1a93af14-d715-11e6-9542-3224611154ef.png)

**Comment by mukeshthawani** [comment]
Which version you've installed? Can you try the latest one?

**Comment by saldous** [comment]
My Podfile has:

pod 'FAQView'

Which installed v0.2.1

**Comment by mukeshthawani** [comment]
Update it to the latest version then it will work fine. Use this command `pod update FAQView` to update.

**Comment by saldous** [comment]
It still installs 0.2.1

**Comment by saldous** [comment]
got it, 0.2.4 installed and works. Thank you.
