### ISSUE TITLE
Bug with scrolling off screen

### ISSUE THREAD

**Issue by DavidLari** [mukeshthawani/FAQView#9]
If an expanded cell scrolls off the screen, when it scrolls back on, it is no longer expanded. However, the section number is still in the expandedCells array. Because of this, when you tap on the cell to expand the cell, it won't expand. You must tap it a second time to get it to expand. 

I have tried to think of a way to fix this, but there are a couple of different ways to make FAQView behave. One would be to change it so as cells scroll back onto the screen, if they were previously, expanded, show them as expanded.

Or, if leaving them unexpanded is desirable, then somehow the section number must be removed from the expandedCells array when a cell scrolls off.

**Comment by mukeshthawani** [comment]
It's fixed now.
